export const Misc = {
  MAX_ROUNDS: 5,
  ZERO_XP: 5000,
  ZERO_ACCURACY: 5000,
  MAX_XP: 250,
  ADS_PER_COUNTER: 4,
  MAX_SEARCH_ATTEMPTS: 10,
  REQUIRED_IMAGES: 0,
  UNLOCK_ALL_LVL: 4, 
  REQUIRED_QUALITY: 0.65,
  SEARCH_DELAY_MS: 80,
  COINS_PER_PAID_GAME: 10
};
